#+TITLE: rj-mode layer

* Table of Contents                                        :TOC_4_gh:noexport:
- [[#description][Description]]
- [[#install][Install]]
- [[#configuration][Configuration]]
- [[#key-bindings][Key bindings]]

* Description

=rj-mode= is a minor mode to automatically vertically-recenter the cursor
following many jumping motions, including:

- All Evil motion commands that add to the jumplist

  To do this, rj hooks into =post-command-hook= looking for any command
  with the command property =:jump=, which evil uses to mark commands that
  should store a jump point before executing.

- Evil jumplist navigation (e.g. ~C-o~ / ~C-z~)

  rj hooks into =evil-jumps-post-jump-hook= to catch these.
 
- A configurable list of extra commands, including by default jumps to marks,
  next error, and changelist navigation

  rj installs after-advice to every command in =rj-extra-commands= when the
  mode is activated (and cleans up when it's turned off).

I'm favouring hooks over advice where possible.

* Install

To use this configuration layer, clone this repo to a Spacemacs layer path
and add it to your =~/.spacemacs=. You will need to add =rj-mode= to the
existing =dotspacemacs-configuration-layers= list in this file.

* Configuration

=rj-blacklist= is a list of command name patterns to be excluded, that is, rj
won't recenter after these commands. This is useful for when  ="^evil-snipe-[tTfF]$"= is on
the blacklist (most of the time, when I use it, it's not much of a real jump).

=rj-extra-commands= is a list of command names to add rj's behaviour to. rj
will add after-advice to each of these commands when it's activated, and
remove it when it's deactivated.

If you edit =rj-extra-commands=, toggle =rj-mode= off and on again for it to
take effect.

* Key bindings

| Key Binding | Description              |
|-------------+--------------------------|
| ~SPC t R~   | Toggle =rj-mode= locally |
| ~SPC t C-R~ | Toggle =global-rj-mode=  |
